export const PROJECTS = [
  {
    id: "mess-manager-os",
    title: "Mess Management System",
    description:
      "A full-stack SaaS platform for mess management featuring role-based dashboards, automated monthly billing, dynamic meal rate calculation, utility expense distribution, meal tracking, notices, complaints, reports, and AI-assisted menu planning. Built with a scalable architecture using Next.js, Express.js, MongoDB, and TypeScript.",
    image: "/assets/mess.png",
    tags: [
      "Next.js 16",
      "React 19",
      "Node.js",
      "Express.js",
      "MongoDB",
      "TypeScript",
    ],
    liveUrl: "http://72.61.115.32:3005/",
    githubUrl: "https://github.com/nurulla-hasan/mess_os_client",
    role: "Full-Stack Developer",
    duration: "2024 – Present",
    features: [
      "Role-based dashboards for managers, members, and admins with granular access control",
      "Automated monthly billing with dynamic meal rate calculation and equal-share utility cost distribution",
      "Real-time meal tracking system with daily meal count management and meal on/off toggle",
      "AI-powered menu planner that automates daily grocery lists based on budget limits and dietary preferences",
      "Market scheduler for automated daily grocery procurement workflows",
      "Notice board, complaint management, and report generation systems",
      "Comprehensive analytics dashboard with monthly expense breakdowns and member-wise reports",
    ],
    challenges: [
      "Designed a scalable multi-tenant architecture supporting multiple mess groups with isolated data",
      "Implemented complex billing logic handling dynamic meal rates, utility splits, and carry-forward balances",
      "Built an optimized server-side data fetching layer with automated JWT validation and Next.js caching (revalidateTag)",
      "Engineered URL-state filtering with debounced navigation, reducing redundant API calls by 40%",
    ],
    screenshots: [
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
      "/assets/mess.png",
    ],
  },

  {
    id: "mouza-map-calculator",
    title: "Mouza Map Pro",
    description:
      "A proprietary geospatial plotting platform built with React and Konva.js for accurate land measurement, interactive map annotation, intelligent label placement, and instant PDF report generation. Designed for real-world land survey workflows with high-performance canvas rendering.",
    image: "/assets/mouza.png",
    tags: ["React", "Konva.js", "Zustand", "jsPDF"],
    liveUrl: "https://mouzamappro.com",
    githubUrl: "https://github.com/nurulla-hasan/mouza_map_pro",
    role: "Frontend Developer",
    duration: "2024",
    features: [
      "High-performance 2D geospatial plotting tool with Konva.js canvas rendering",
      "Shoelace algorithm implementation converting pixel distances into exact physical land areas (SqFt, Shotok)",
      "Interactive map annotation with drag-and-drop point placement and real-time area calculation",
      "Intelligent label placement with custom physics-based repulsion algorithm to prevent overlapping",
      "Client-side PDF processing (pdfjs) delivering instant, scale-accurate A4 reports without server overhead",
      "Zustand-powered global state management for complex canvas interactions",
      "Responsive UI supporting both desktop and tablet workflows",
    ],
    challenges: [
      "Implemented complex geometric algorithms (Shoelace formula) for accurate land area calculation from arbitrary polygons",
      "Built a custom physics-based label repulsion system to prevent text overlap on dense map annotations",
      "Achieved high-performance canvas rendering with Konva.js handling hundreds of interactive elements",
      "Engineered client-side PDF generation that maintains pixel-perfect accuracy at print scale",
    ],
    screenshots: [
      "/assets/mouza.png",
      "/assets/mouza.png",
      "/assets/mouza.png",
      "/assets/mouza.png",
      "/assets/mouza.png",
      "/assets/mouza.png",
      "/assets/mouza.png",
    ],
  },

  {
    id: "mentorip",
    title: "MentorIP — Global IP Law Firm",
    description:
      "A high-performance corporate website for an international Intellectual Property law firm featuring advanced SEO, JSON-LD structured data, dynamic Table of Contents generation, On-Demand ISR, and polished user experiences powered by Framer Motion.",
    image: "/assets/mentorip.png",
    tags: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS v4",
      "Framer Motion",
    ],
    liveUrl: "https://mentorip.com",
    githubUrl: "https://github.com/nurulla-hasan/mentorip_website",
    role: "Frontend Developer",
    duration: "2025",
    features: [
      "Advanced JSON-LD structured data for SEO with rich snippets support",
      "Dynamic HTML Table of Contents parsing for long-form legal content pages",
      "⌘K global command palette for quick navigation across the entire website",
      "On-Demand ISR (revalidateTag) for instant content updates without full rebuilds",
      "Polished animations and micro-interactions powered by Framer Motion",
      "Fully responsive design optimized for desktop, tablet, and mobile devices",
      "Multi-page architecture with services, blog, team, and contact sections",
    ],
    challenges: [
      "Implemented dynamic Table of Contents generation by parsing HTML headings from CMS content",
      "Built a global command palette (⌘K) with fuzzy search across all pages and content",
      "Optimized content caching with On-Demand ISR for real-time content updates",
      "Achieved 90+ Lighthouse scores across Performance, SEO, Accessibility, and Best Practices",
    ],
    screenshots: ["/assets/mentorip.png"],
  },

  {
    id: "wedding-marketplace",
    title: "Wedding Marketplace & Vendor Platform",
    description:
      "A modern marketplace connecting couples with wedding vendors through smart search, advanced filtering, venue comparison, quotation workflows, and dedicated user/vendor dashboards with reusable frontend architecture.",
    image: "/assets/elevetor.png",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "shadcn/ui"],
    liveUrl: "https://elevator-website-six.vercel.app/",
    githubUrl: "https://github.com/nurulla-hasan/elevator_website",
    role: "Frontend Developer",
    duration: "2024",
    features: [
      "Smart search with advanced filtering for wedding vendors by category, location, and budget",
      "Venue comparison tool allowing side-by-side evaluation of multiple vendors",
      "Quotation request workflow connecting couples directly with vendors",
      "Dedicated user and vendor dashboards with role-based access control",
      "Reusable component architecture for scalable frontend development",
      "Responsive design optimized for mobile-first wedding planning experience",
    ],
    challenges: [
      "Built a complex filtering system with multiple simultaneous filter criteria and URL-state sync",
      "Designed a reusable component library that reduced development time across similar pages",
      "Implemented role-based dashboard views with shared component architecture",
    ],
    screenshots: ["/assets/elevetor.png"],
  },

  {
    id: "recycle-mart",
    title: "Recycle Mart — Buy & Sell Used Goods",
    description:
      "A modern marketplace for buying and selling pre-owned products featuring multilingual support, real-time messaging, secure authentication, Cloudinary-powered image management, and a responsive shopping experience.",
    image: "/assets/recycle.png",
    tags: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS v4",
      "shadcn/ui",
      "Socket.IO",
      "next-intl",
    ],
    liveUrl: "https://recyclemart.com.bd",
    githubUrl: "https://github.com/nurulla-hasan/recyclemart_website",
    role: "Frontend Developer",
    duration: "2025",
    features: [
      "Multilingual support (Bangla/English) with next-intl for full i18n coverage",
      "Real-time messaging between buyers and sellers powered by Socket.IO",
      "Secure authentication with JWT-based session management",
      "Cloudinary-powered image upload and optimization for product listings",
      "Advanced product search and category-based filtering",
      "Responsive shopping experience optimized for mobile and desktop users",
    ],
    challenges: [
      "Integrated real-time messaging with Socket.IO maintaining persistent connections",
      "Implemented full multilingual support with dynamic content translation",
      "Built Cloudinary integration for efficient image management with automatic optimization",
    ],
    screenshots: ["/assets/recycle.png"],
  },

  {
    id: "cookbook-recipe",
    title: "Cookbook Recipe & Meal Planner",
    description:
      "A recipe and meal-planning application featuring protected routes, reusable frontend architecture, responsive UI, optimized user interactions, and personalized meal management workflows.",
    image: "/assets/jaykou.png",
    tags: ["React", "Redux", "JavaScript", "Tailwind CSS", "shadcn/ui"],
    liveUrl: "https://koumanisdietapp.com",
    githubUrl: "https://github.com/nurulla-hasan/cookbook-recipe-website",
    role: "Frontend Developer",
    duration: "2024",
    features: [
      "Personalized meal planning with custom recipe management",
      "Protected routes with role-based authentication and authorization",
      "Redux-powered global state management for complex meal workflows",
      "Recipe search and filtering by ingredients, cuisine, and dietary preferences",
      "Responsive UI with optimized user interactions and smooth transitions",
      "Reusable component architecture following best practices",
    ],
    challenges: [
      "Designed a scalable Redux store architecture for complex meal planning state",
      "Implemented protected routing with seamless authentication flow",
      "Built reusable UI components that maintained consistency across the application",
    ],
    screenshots: ["/assets/jaykou.png"],
  },

  {
    id: "binksanders",
    title: "Bink Sanders — Microlearning Platform",
    description:
      "An interactive microlearning platform featuring module-based learning paths, survey-driven assessments on workplace safety and inclusion, rich progress tracking with localStorage persistence, and dynamic theming. Built with Next.js 16 App Router, Radix UI, and Recharts for data-driven insights.",
    image: "/assets/binksanders.png",
    tags: [
      "Next.js 16",
      "TypeScript",
      "Tailwind CSS v4",
      "shadcn/ui",
      "Radix UI",
      "TipTap",
      "Recharts",
      "Framer Motion",
    ],
    liveUrl: "https://binksanders-website.vercel.app/",
    githubUrl: "https://github.com/nurulla-hasan/binksanders_website",
    role: "Frontend Developer",
    duration: "2025",
    features: [
      "Module-based learning paths with structured course progression",
      "Survey-driven assessments on workplace safety and inclusion topics",
      "Rich progress tracking with localStorage persistence across sessions",
      "Data-driven insights and analytics dashboards powered by Recharts",
      "Dynamic theming with customizable color schemes",
      "Rich text editing capabilities with TipTap editor integration",
      "Smooth animations and page transitions with Framer Motion",
    ],
    challenges: [
      "Built a complex module progression system with state persistence using localStorage",
      "Integrated Recharts for interactive data visualization of learning progress",
      "Implemented dynamic theming that propagates across all UI components",
      "Designed survey assessment logic with branching question flows",
    ],
    screenshots: ["/assets/binksanders.png"],
  },
];
